spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1GB
      max-request-size: 1GB
      location: uploads/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    mvc:
      matching-strategy:
      - matching-strategy=ant_path_matcher

jwt:
  secret: ${JWT_SECRET}
